"""haro2_initial

Revision ID: 5fdbee1e1b1c
Revises: 98ecbc1e5b66
Create Date: 2023-02-16 05:58:23.095273

"""
# Ref: https://github.com/beproud/beproudbot/issues/241
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fdbee1e1b1c'
down_revision = '98ecbc1e5b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Unicode(length=249), nullable=True),
    sa.Column('name', sa.Unicode(length=249), nullable=False),
    sa.Column('status', sa.Unicode(length=249), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_resource')
    # ### end Alembic commands ###
