"""add resource model

Revision ID: 8e7a2acd24b8
Revises: 919388975e00
Create Date: 2019-01-31 13:41:01.788909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8e7a2acd24b8"
down_revision = "919388975e00"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resource",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Unicode(length=249), nullable=False),
        sa.Column("name", sa.Unicode(length=249), nullable=False),
        sa.Column("status", sa.Unicode(length=249), nullable=True),
        sa.Column("ctime", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resource")
    # ### end Alembic commands ###
