"""add emergency models

Revision ID: 98ecbc1e5b66
Revises: 8e7a2acd24b8
Create Date: 2019-04-26 14:07:15.245678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "98ecbc1e5b66"
down_revision = "8e7a2acd24b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "emergency_timeline",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Unicode(length=9), nullable=False),
        sa.Column("room", sa.Unicode(length=9), nullable=False),
        sa.Column("title", sa.Unicode(length=128), nullable=False),
        sa.Column("is_closed", sa.BOOLEAN(), nullable=False),
        sa.Column("ctime", sa.DateTime(), nullable=False),
        sa.Column("utime", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "timeline_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timeline_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Unicode(length=9), nullable=False),
        sa.Column("ctime", sa.DateTime(), nullable=False),
        sa.Column("utime", sa.DateTime(), nullable=False),
        sa.Column("entry", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["timeline_id"],
            ["emergency_timeline.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("timeline_log")
    op.drop_table("emergency_timeline")
    # ### end Alembic commands ###
