"""my message

Revision ID: b4743eca24b3
Revises: 919388975e00
Create Date: 2017-12-27 21:06:05.307740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4743eca24b3'
down_revision = '919388975e00'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
