"""my message

Revision ID: e56edd908355
Revises: b4743eca24b3
Create Date: 2017-12-27 21:09:29.537652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e56edd908355'
down_revision = 'b4743eca24b3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
