"""create table

Revision ID: 11673cfcc25a
Revises: 
Create Date: 2017-01-17 21:08:35.664728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11673cfcc25a'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kintai_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Unicode(length=100), nullable=False),
    sa.Column('is_workon', sa.Boolean(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('redbull_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Unicode(length=100), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('water_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Unicode(length=100), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_history')
    op.drop_table('redbull_history')
    op.drop_table('kintai_history')
    ### end Alembic commands ###
