"""create user table

Revision ID: 310b8ce06e2e
Revises: 11673cfcc25a
Create Date: 2017-01-25 09:19:03.179054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310b8ce06e2e'
down_revision = '11673cfcc25a'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_id', sa.Unicode(length=100), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slack_id')
    )
    op.create_table('user_alias_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.Unicode(length=100), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_alias_name')
    op.drop_table('user')
    ### end Alembic commands ###
