"""create water_history table

Revision ID: 4e4c7075ffb0
Revises: 1689277c2bb6
Create Date: 2016-12-21 11:53:44.647558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e4c7075ffb0'
down_revision = '1689277c2bb6'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('who', sa.Unicode(length=100), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_history')
    ### end Alembic commands ###
