"""create thx table

Revision ID: 610f35027fb9
Revises: 2ffb0d589280
Create Date: 2017-03-12 14:19:24.614247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610f35027fb9'
down_revision = '2ffb0d589280'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleaning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_id', sa.Unicode(length=11), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thx_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Unicode(length=100), nullable=False),
    sa.Column('from_user_id', sa.Unicode(length=100), nullable=False),
    sa.Column('word', sa.Unicode(length=1024), nullable=False),
    sa.Column('channel_id', sa.Unicode(length=100), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thx_history')
    op.drop_table('cleaning')
    ### end Alembic commands ###
