"""create water_history table

Revision ID: b77d60c7a60e
Revises: 
Create Date: 2016-12-21 01:49:45.103499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b77d60c7a60e'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kintai_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('who', sa.Unicode(length=100), nullable=True),
    sa.Column('is_workon', sa.Boolean(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kintai_history')
    ### end Alembic commands ###
