"""create kudo table

Revision ID: f3760a7efcea
Revises: 2ffb0d589280
Create Date: 2017-02-19 15:52:26.035966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3760a7efcea'
down_revision = '2ffb0d589280'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kudo_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.Column('from_user_id', sa.Unicode(length=100), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kudo_history')
    ### end Alembic commands ###
