"""create term table

Revision ID: fc53ecf62104
Revises: 2ffb0d589280
Create Date: 2017-03-22 01:49:07.492263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc53ecf62104'
down_revision = '2ffb0d589280'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleaning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_id', sa.Unicode(length=11), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('created_command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.Column('creator', sa.Unicode(length=100), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_command', sa.Integer(), nullable=True),
    sa.Column('word', sa.Unicode(), nullable=False),
    sa.Column('creator', sa.Unicode(length=100), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_command'], ['created_command.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('term')
    op.drop_table('created_command')
    op.drop_table('cleaning')
    ### end Alembic commands ###
